README.md
Added installed packages to README
[REPORT: Incident Information](https://app.gitkraken.com/glo/card/0455d5887943454db17e98183d7967e0)
=> Added extra content to README

README.md
Incident Information report checked and all fields are present and match with the mobile version of OneResponse - Management.
Added extra content to README.
[REPORT: Incident Information](https://app.gitkraken.com/glo/card/0455d5887943454db17e98183d7967e0)
=> Incident information

src/components/subPages/PatientReport/PatientReport.component.jsx
Patient Details report (including Next of Kin) match the mobile version of OneResponse - Management.
[REPORT: Patient Details](https://app.gitkraken.com/glo/card/9b459edcc39b4b16b17b0d105240bd03)
=> Patient Details (and Next of Kin) match

.vscode/settings.json, src/components/subPages/PatientReport/PatientReport.component.jsx
Made a quick change to Airways Management.
=> SB-7: Airways management

src/components/subPages/PatientReport/PatientReport.component.jsx
Added Surgical Cric., Suction and Thoracostomy usage fields to Airways Management report.
[REPORT: Airways Management](https://app.gitkraken.com/glo/card/90beff979be941498bd57fc0abe2d642)
=> SB-7 : Airways Management

src/components/subPages/PatientReport/PatientReport.component.jsx
No changes for Cardiac Arrest needed. Removed unused HeadingFour import.
=> SB-8 : No changes needed. Removed unused HeadingFour import.

src/components/subPages/PatientReport/PatientReport.component.jsx
Added 'Patient Own Meds Transported' (patientOwnMeds' field to Transport Options. Transport Options report now matches the mobile version of OneResponse - Management.
[REPORT: Transport Options](https://app.gitkraken.com/glo/card/87f2a35d00454b2b8d24aa8c70b23641)
=> SB-9 : Added patientOwnMeds field to Transport Options.

src/components/subPages/PatientReport/PatientReport.component.jsx
Correct 'Is there reason to doubt the Patients capacity?' field in Mental Capacity Act.
[REPORT: Capacity to Consent](https://app.gitkraken.com/glo/card/e4b0e647ab7c49a0a603e213a8833fd2)
=> SB-13 : Corrected field in Mental Capacity Act section.

README.md, src/components/subPages/PatientReport/PatientReport.component.jsx
Made changes to the Triage and Pathfinder Support report section, as well as the README file. Please note that Joint Decision Making has not yet been adjusted - need to check that the table format is not needed in the newest version of OneResponse - Management.
[REPORT: Triage and Pathfinder Support](https://app.gitkraken.com/glo/card/6b2bd53eb32147e195f598a52460c455)
=> SB-10: Triage and Pathfinder Support

README.md
Only made changes to the README file. The Trauma Management tile matches the OneResponse - Management mobile version.
[REPORT: Trauma Management](https://app.gitkraken.com/glo/card/95901f1e13dc486a9c01bd254b529a0f)
=> SB-11: Made changes to the README

src/components/UI/Header/Header.component.jsx, src/components/subPages/PatientReport/PatientReport.component.jsx
Joint Decision Making now has a vertical layout to match the same report in the OneResponse - Management mobile app.
[REPORT: Triage and Pathfinder Support](https://app.gitkraken.com/glo/card/6b2bd53eb32147e195f598a52460c455)
=> SB-10: Joint Decision Making now vertical

src/App.js, src/components/UI/PatientList/PatientList.component.jsx, src/components/pages/Report/Report.component.jsx, src/components/subPages/DiagnosisOfDeath/DiagnosisOfDeath.component.jsx, src/components/subPages/PatientReport/PatientReport.component.jsx
[subPage: Diagnosis of Death](https://app.gitkraken.com/glo/card/7e90cc893dbe4d1fb7cc9f6294d4e65a)
=> SB-40: Started work on Diagnosis of Death and PatientItem

src/components/pages/Report/Report.component.jsx, src/components/subPages/DiagnosisOfDeath/DiagnosisOfDeath.component.jsx, src/components/subPages/Notes/Notes.component.jsx
Completed the Previous Medical History section of notes.
Also hopefully the last change needed to DiagnosisOfDeath.component: The expected Death section was only in one column, I fixed that to be in two columns now.
[NOTES: Previous Medical History](https://app.gitkraken.com/glo/card/0c5f64f87de54933835888eda967807f)
=> SB-33 Completed the Previous Medical History section of Notes

src/components/pages/Report/Report.component.jsx, src/components/subPages/DiagnosisOfDeath/DiagnosisOfDeath.component.jsx, src/components/subPages/Notes/Notes.component.jsx
I completed the Social History section of Notes. Smooth sailing, no issues or bugs that I could see.
[NOTES: Social History](https://app.gitkraken.com/glo/card/3945b08a7f2e43d68ed2a51cffd773cb)
=> SB-34 Completed Social History section of Notes

src/components/pages/Report/Report.component.jsx, src/components/subPages/DiagnosisOfDeath/DiagnosisOfDeath.component.jsx, src/components/subPages/Notes/Notes.component.jsx
I completed the Family History section of notes. Smooth sailing, no issues or bugs found.
[NOTES: Family History](https://app.gitkraken.com/glo/card/377898f5f21e42198b0338de886a8354)
=> SB-35 Completed the Family History section of Notes

src/components/pages/Report/Report.component.jsx, src/components/subPages/DiagnosisOfDeath/DiagnosisOfDeath.component.jsx, src/components/subPages/Notes/Notes.component.jsx
Completed the On Examination section of Notes. Smooth sailing, no issues or bugs that I could find.
[NOTES: On Examination](https://app.gitkraken.com/glo/card/1753821293a54c9a948bd4a1e4800fee)
=> SB-36 Completed the On Examination section of Notes

package-lock.json, src/components/subPages/Notes/Notes.component.jsx
Completed the Impression section of notes. Smooth-sailing, no issues or bugs that I could see.
[NOTES: Impression](https://app.gitkraken.com/glo/card/bfe95922e6934bff9a90e9b3b1c16502)
=> SB-37 Completed the Impression section of Notes

src/App.js, src/components/UI/Header/Header.component.jsx, src/components/UI/PatientList/PatientList.component.jsx, src/components/UI/PatientSearchMenu/PatientSearchMenu.component.jsx, src/components/UI/ReportHeader/ReportHeader.component.jsx, src/components/pages/Report/Report.component.jsx
SB-24: Added Header (secondary-header) buttons: Save, Search, Log Out.
SB-25: Added initial PatientSearchMenu pop-out from the left side of the screen.
=> SB-24: Added Header(secondary) buttons, and initial PatientSearchMenu

src/components/subPages/Notes/Notes.component.jsx
I Completed the Plan/Treatment section of Notes. Smooth-sailing, no issues or bugs that I could find.
[NOTES: Plan / Treatment](https://app.gitkraken.com/glo/card/f2a6cf1c12334ddeaaab3039cb5e013d)
=> SB-38 Completed the Plan/Treatment section of Notes

src/components/subPages/Notes/Notes.component.jsx
Completed the Additional Information section of Notes. Smooth sailing, no issues or bugs that I could find.
[NOTES: Additional Information](https://app.gitkraken.com/glo/card/e720e982703345e09e46c91ad4e5beb0)
=> SB-39 Completed the Additional Information section of Notes

src/components/UI/PatientItem/PatientItem.component.jsx, src/components/UI/PatientNameHeader/PatientNameHeader.component.jsx, src/components/UI/PatientSearchMenu/PatientSearchMenu.component.jsx, src/components/subPages/PatientReport/PatientReport.component.jsx
Added the following search parameters:
- Incident No.
- Call Sign
- ePR User
- Patient Firstname
- Patient Surname
- NHS No
- Receiving Location
Still need to add ePR types
=> SB-42: Added search parameters except for ePR types

debug.log, src/components/subPages/DiagnosisOfDeath/DiagnosisOfDeath.component.jsx
I completed the Attendance and Relatives section of DoD.
I've noticed there are some responsiveness issues however, so I'll open an Issues card and detail them there.
[DIAGNOSISOFDEATH: Attendance and Relatives](https://app.gitkraken.com/glo/card/e1115251cf17411cbfc33f25d1c4ff2b)
=> SB40, SB41 Completed the Attendance and Relatives section of DoD

src/components/UI/Header/Header.component.jsx, src/components/UI/PatientSearchMenu/PatientSearchMenu.component.jsx
Added search functionality to the PatientSearchMenu (right-hand side slide out) component.
Search functionality added for: Incident No., Call Sign, ePR User, Patient Firstname, Patient Surname, NHS No., and Receiving Location.
[UI: Patient / Incident Search](https://app.gitkraken.com/glo/card/6c069a94d5a74ff09c9f7e0455585820)
=> SB-42: Added search functionality to PatientSearchMenu

src/components/UI/PatientItem/PatientItem.component.jsx
I put the patient item icon in a "flex-direction:column" container and put the PVN_Transport from the API.
=> SB-28, I've added PVN_Transport and a container to wrap that and the icon in a flex column
